# Generated by Django 3.2.5 on 2021-08-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.professional'),
        ),
    ]
